import { getAssetPath } from "./getAssetPath";

export type PortfolioCategory = "Logos" | "Banners" | "MockUps" | "Videos" | "Social Media Posts" | "Meta-Ads" | "Websites";

export interface Project {
  id: number;
  title: string;
  category: PortfolioCategory;
  description: string;
  image: string; // local path
  mediaType?: "image" | "video"; // For handling videos vs images
  videoUrl?: string; // Video file path
  technologies: string[];
  liveUrl?: string;
  features: string[];
}

// Helper function to create asset path
const asset = (path: string) => getAssetPath(path);

export const portfolioProjects: Project[] = [
  // ===== VIDEOS FOLDER - Only Videos (6 items) =====
  {
    id: 1001,
    title: "VIDEO-1",
    category: "Videos",
    description: "Professional video content for digital marketing and branding.",
    image: asset("/src/assets/images/Videos/VIDEO-1.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-1.mp4"),
    technologies: ["Video Production", "Editing", "Post-Production"],
    features: ["HD Quality", "Professional Editing", "Marketing Ready"],
  },
  {
    id: 1002,
    title: "VIDEO-2",
    category: "Videos",
    description: "Engaging video content designed to capture audience attention.",
    image: asset("/src/assets/images/Videos/VIDEO-2.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-2.mp4"),
    technologies: ["Cinematography", "Color Grading", "Audio Design"],
    features: ["Storytelling", "Visual Effects", "Professional Audio"],
  },
  {
    id: 1003,
    title: "VIDEO-3",
    category: "Videos",
    description: "Creative video content for digital marketing campaigns.",
    image: asset("/src/assets/images/Videos/VIDEO-3.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-3.mp4"),
    technologies: ["Motion Design", "Animation", "Video Editing"],
    features: ["Dynamic Transitions", "Brand Consistency", "Optimized Delivery"],
  },
  {
    id: 1004,
    title: "VIDEO-4",
    category: "Videos",
    description: "Professional video production with modern visual techniques.",
    image: asset("/src/assets/images/Videos/VIDEO-4.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-4.mp4"),
    technologies: ["After Effects", "Premiere Pro", "Creative Direction"],
    features: ["High Production Value", "Seamless Editing", "Compelling Narrative"],
  },
  {
    id: 1005,
    title: "VIDEO-5",
    category: "Videos",
    description: "Strategic video content designed for maximum engagement.",
    image: asset("/src/assets/images/Videos/VIDEO-5.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-5.mp4"),
    technologies: ["Video Strategy", "Content Creation", "Distribution"],
    features: ["Audience Targeting", "Platform Optimization", "Performance Tracking"],
  },
  {
    id: 1006,
    title: "VIDEO-6",
    category: "Videos",
    description: "Premium video content showcasing brand identity and values.",
    image: asset("/src/assets/images/Videos/VIDEO-6.mp4"),
    mediaType: "video",
    videoUrl: asset("/src/assets/images/Videos/VIDEO-6.mp4"),
    technologies: ["Brand Video", "Corporate Production", "Multi-Platform"],
    features: ["Brand Alignment", "Professional Quality", "Versatile Formats"],
  },

  // ===== META-ADS FOLDER - Only Meta Ads (11 items) =====
  {
    id: 2001,
    title: "Meta Ad 1",
    category: "Meta-Ads",
    description: "High-converting Facebook and Instagram ad creative for digital campaigns.",
    image: asset("/src/assets/images/META-ADS/1.jpg"),
    technologies: ["Meta Ads Manager", "A/B Testing", "Analytics"],
    features: ["High CTR", "Targeted Audience", "Conversion Optimized"],
  },
  {
    id: 2002,
    title: "Meta Ad 2",
    category: "Meta-Ads",
    description: "Engaging social media advertisement designed for maximum reach and engagement.",
    image: asset("/src/assets/images/META-ADS/2.jpg"),
    technologies: ["Creative Design", "Copywriting", "Performance Marketing"],
    features: ["Eye-Catching Design", "Clear CTA", "Mobile-First"],
  },
  {
    id: 2003,
    title: "Meta Ad 3",
    category: "Meta-Ads",
    description: "Strategic ad creative optimized for Facebook and Instagram feeds.",
    image: asset("/src/assets/images/META-ADS/3.jpg"),
    technologies: ["Social Media Marketing", "Creative Strategy", "ROAS Optimization"],
    features: ["Feed Native", "Brand Consistent", "Scalable Creative"],
  },
  {
    id: 2004,
    title: "Meta Ad 4",
    category: "Meta-Ads",
    description: "Professional ad design targeting specific demographics and interests.",
    image: asset("/src/assets/images/META-ADS/4.jpg"),
    technologies: ["Audience Segmentation", "Creative Testing", "Funnel Optimization"],
    features: ["Demographic Targeting", "Creative Variants", "Performance Tracking"],
  },
  {
    id: 2005,
    title: "Meta Ad 5",
    category: "Meta-Ads",
    description: "Convert-focused ad creative with strong visual hierarchy and messaging.",
    image: asset("/src/assets/images/META-ADS/5.jpg"),
    technologies: ["Conversion Optimization", "Landing Page Sync", "Retargeting"],
    features: ["Conversion-Focused", "Message Clarity", "Action-Oriented"],
  },
  {
    id: 2006,
    title: "Meta Ad 6",
    category: "Meta-Ads",
    description: "Brand awareness campaign ad with compelling visual storytelling.",
    image: asset("/src/assets/images/META-ADS/6.jpg"),
    technologies: ["Brand Marketing", "Storytelling", "Engagement Strategy"],
    features: ["Brand Awareness", "Story-Driven", "Share-Worthy"],
  },
  {
    id: 2007,
    title: "Meta Ad 7",
    category: "Meta-Ads",
    description: "Performance-driven ad creative with data-backed design decisions.",
    image: asset("/src/assets/images/META-ADS/7.jpg"),
    technologies: ["Data-Driven Design", "Performance Analytics", "Iterative Testing"],
    features: ["Data-Backed", "Continuous Optimization", "Measurable Results"],
  },
  {
    id: 2008,
    title: "Meta Ad 8",
    category: "Meta-Ads",
    description: "Retargeting ad creative designed to bring visitors back to convert.",
    image: asset("/src/assets/images/META-ADS/8.jpg"),
    technologies: ["Retargeting", "Dynamic Ads", "Pixel Integration"],
    features: ["Retargeting Optimized", "Personalized", "Recovery Focused"],
  },
  {
    id: 2009,
    title: "Meta Ad 9",
    category: "Meta-Ads",
    description: "Multi-platform ad creative optimized for both Facebook and Instagram.",
    image: asset("/src/assets/images/META-ADS/9.jpg"),
    technologies: ["Cross-Platform", "Format Adaptation", "Consistent Branding"],
    features: ["Multi-Platform", "Format Optimized", "Brand Consistent"],
  },
  {
    id: 2010,
    title: "Meta Ad 10",
    category: "Meta-Ads",
    description: "E-commerce focused ad creative showcasing products and promotions.",
    image: asset("/src/assets/images/META-ADS/10.jpg"),
    technologies: ["E-commerce", "Product Photography", "Sales Funnels"],
    features: ["Product Showcase", "Promotion Highlight", "Shop Integration"],
  },
  {
    id: 2011,
    title: "Meta Ad 11",
    category: "Meta-Ads",
    description: "Advanced ad creative with sophisticated targeting and messaging.",
    image: asset("/src/assets/images/META-ADS/11.jpg"),
    technologies: ["Advanced Targeting", "Creative Innovation", "Campaign Management"],
    features: ["Advanced Targeting", "Innovative Creative", "Comprehensive Management"],
  },

  // ===== MOCKUPS FOLDER - Only Mockups (17 items) =====
  {
    id: 3001,
    title: "MOCKUP-1",
    category: "MockUps",
    description: "Professional product presentation mockup showcasing design and layout.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-1.png"),
    technologies: ["3D Rendering", "Product Design", "Visualization"],
    features: ["Realistic Presentation", "Multiple Angles", "Brand Integration"],
  },
  {
    id: 3002,
    title: "MOCKUP-2",
    category: "MockUps",
    description: "High-fidelity mockup demonstrating product features and aesthetics.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-2.png"),
    technologies: ["Mockup Design", "Photography", "Post-Production"],
    features: ["High Fidelity", "Feature Showcase", "Professional Quality"],
  },
  {
    id: 3003,
    title: "MOCKUP-3",
    category: "MockUps",
    description: "Creative mockup presentation for marketing and sales materials.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-3.png"),
    technologies: ["Creative Direction", "Brand Application", "Marketing Materials"],
    features: ["Creative Layout", "Brand Application", "Marketing Ready"],
  },
  {
    id: 3004,
    title: "MOCKUP-4",
    category: "MockUps",
    description: "Website and application mockup showcasing user interface design.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-4.png"),
    technologies: ["UI/UX Design", "Wireframing", "Prototyping"],
    features: ["UI Showcase", "User Experience", "Interactive Elements"],
  },
  {
    id: 3005,
    title: "MOCKUP-5",
    category: "MockUps",
    description: "Device-specific mockup displaying responsive design across platforms.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-5.png"),
    technologies: ["Responsive Design", "Device Adaptation", "Cross-Platform"],
    features: ["Responsive Layout", "Device Specific", "Platform Optimized"],
  },
  {
    id: 3006,
    title: "MOCKUP-6",
    category: "MockUps",
    description: "Branding mockup presenting visual identity and design system.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-6.jpg"),
    technologies: ["Brand Identity", "Design System", "Visual Language"],
    features: ["Brand Consistency", "Design System", "Visual Identity"],
  },
  {
    id: 3007,
    title: "MOCKUP-7",
    category: "MockUps",
    description: "Packaging mockup showcasing product presentation and branding.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-7.jpg"),
    technologies: ["Packaging Design", "Print Production", "Brand Application"],
    features: ["Packaging Design", "Print Ready", "Brand Alignment"],
  },
  {
    id: 3008,
    title: "MOCKUP-8",
    category: "MockUps",
    description: "Environmental mockup demonstrating brand presence in physical spaces.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-8.jpg"),
    technologies: ["Environmental Design", "Spatial Branding", "Visualization"],
    features: ["Environmental Integration", "Spatial Design", "Brand Presence"],
  },
  {
    id: 3009,
    title: "MOCKUP-9",
    category: "MockUps",
    description: "Social media mockup showcasing content across various platforms.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-9.jpg"),
    technologies: ["Social Media Design", "Content Creation", "Platform Optimization"],
    features: ["Multi-Platform", "Content Showcase", "Platform Specific"],
  },
  {
    id: 3010,
    title: "MOCKUP-10",
    category: "MockUps",
    description: "Dashboard and analytics mockup displaying data visualization.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-10.jpg"),
    technologies: ["Data Visualization", "Dashboard Design", "Analytics UI"],
    features: ["Data Presentation", "Dashboard Layout", "User Analytics"],
  },
  {
    id: 3011,
    title: "MOCKUP-11",
    category: "MockUps",
    description: "Mobile application mockup showcasing app interface and features.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-11.jpg"),
    technologies: ["Mobile UI", "App Design", "Touch Interaction"],
    features: ["Mobile Optimized", "App Interface", "Touch-Friendly"],
  },
  {
    id: 3012,
    title: "MOCKUP-12",
    category: "MockUps",
    description: "E-commerce mockup displaying online store layout and product pages.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-12.jpg"),
    technologies: ["E-commerce Design", "Shop Layout", "Product Display"],
    features: ["E-commerce Layout", "Product Showcase", "Shopping Experience"],
  },
  {
    id: 3013,
    title: "MOCKUP-13",
    category: "MockUps",
    description: "Print design mockup showcasing marketing materials and collateral.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-13.jpg"),
    technologies: ["Print Design", "Marketing Collateral", "Brand Materials"],
    features: ["Print Quality", "Marketing Materials", "Brand Collateral"],
  },
  {
    id: 3014,
    title: "MOCKUP-14",
    category: "MockUps",
    description: "Landing page mockup demonstrating conversion-focused design.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-14.jpg"),
    technologies: ["Landing Page Design", "Conversion Optimization", "User Flow"],
    features: ["Conversion Focused", "Clear CTA", "User Journey"],
  },
  {
    id: 3015,
    title: "MOCKUP-15",
    category: "MockUps",
    description: "Portfolio mockup showcasing creative work and project presentation.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-15.jpg"),
    technologies: ["Portfolio Design", "Project Showcase", "Creative Presentation"],
    features: ["Portfolio Layout", "Project Display", "Creative Showcase"],
  },
  {
    id: 3016,
    title: "MOCKUP-16",
    category: "MockUps",
    description: "Brand guideline mockup presenting visual identity standards.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-16.jpg"),
    technologies: ["Brand Guidelines", "Style Guide", "Identity Standards"],
    features: ["Brand Standards", "Visual Guidelines", "Consistency Framework"],
  },
  {
    id: 3017,
    title: "MOCKUP-17",
    category: "MockUps",
    description: "Corporate presentation mockup displaying business materials.",
    image: asset("/src/assets/images/MOCKUPS/MOCKUP-17.jpg"),
    technologies: ["Corporate Design", "Business Materials", "Professional Presentation"],
    features: ["Corporate Branding", "Professional Materials", "Business Communication"],
  },

  // ===== LOGOS FOLDER - Only Logos (8 items) =====
  {
    id: 4001,
    title: "LOGO-1",
    category: "Logos",
    description: "Professional logo design with strong brand identity and visual impact.",
    image: asset("/src/assets/images/LOGOS/LOGO-1.png"),
    technologies: ["Logo Design", "Brand Identity", "Vector Graphics"],
    features: ["Scalable Vector", "Brand Identity", "Versatile Application"],
  },
  {
    id: 4002,
    title: "LOGO-2",
    category: "Logos",
    description: "Modern logo creation with clean lines and contemporary aesthetics.",
    image: asset("/src/assets/images/LOGOS/LOGO-2.png"),
    technologies: ["Typography", "Icon Design", "Brand Development"],
    features: ["Modern Aesthetic", "Typography Integration", "Icon Design"],
  },
  {
    id: 4003,
    title: "LOGO-3",
    category: "Logos",
    description: "Creative logo design showcasing unique brand personality and character.",
    image: asset("/src/assets/images/LOGOS/LOGO-3.png"),
    technologies: ["Creative Design", "Brand Personality", "Visual Identity"],
    features: ["Unique Identity", "Brand Personality", "Creative Expression"],
  },
  {
    id: 4004,
    title: "LOGO-4",
    category: "Logos",
    description: "Corporate logo design with professional and trustworthy appearance.",
    image: asset("/src/assets/images/LOGOS/LOGO-4.jpg"),
    technologies: ["Corporate Branding", "Professional Design", "Trust Building"],
    features: ["Corporate Identity", "Professional Look", "Trustworthy Design"],
  },
  {
    id: 4005,
    title: "LOGO-5",
    category: "Logos",
    description: "Bold logo design with strong visual presence and memorable characteristics.",
    image: asset("/src/assets/images/LOGOS/LOGO-5.jpg"),
    technologies: ["Bold Design", "Memorable Branding", "Visual Impact"],
    features: ["Strong Presence", "Memorable Design", "Visual Impact"],
  },
  {
    id: 4006,
    title: "LOGO-6",
    category: "Logos",
    description: "Minimalist logo design focusing on simplicity and clarity.",
    image: asset("/src/assets/images/LOGOS/LOGO-6.png"),
    technologies: ["Minimalism", "Simple Design", "Clean Aesthetics"],
    features: ["Minimalist Approach", "Simple & Clear", "Timeless Design"],
  },
  {
    id: 4007,
    title: "LOGO-7",
    category: "Logos",
    description: "Elegant logo design with sophisticated visual elements and refinement.",
    image: asset("/src/assets/images/LOGOS/LOGO-7.png"),
    technologies: ["Elegant Design", "Sophistication", "Refined Aesthetics"],
    features: ["Elegant Style", "Sophisticated Design", "Refined Look"],
  },
  {
    id: 4008,
    title: "LOGO-8",
    category: "Logos",
    description: "Versatile logo design adaptable to various applications and contexts.",
    image: asset("/src/assets/images/LOGOS/LOGO-8.png"),
    technologies: ["Versatile Design", "Adaptive Branding", "Multi-Context"],
    features: ["Versatile Application", "Adaptive Design", "Multi-Context Use"],
  },

  // ===== BANNERS FOLDER - Only Banners (4 items) =====
  {
    id: 5001,
    title: "BANNER-1",
    category: "Banners",
    description: "Eye-catching banner design optimized for web and social media display.",
    image: asset("/src/assets/images/BANNERS/BANNER-1.jpg"),
    technologies: ["Banner Design", "Web Optimization", "Social Media"],
    features: ["High Visibility", "Web Optimized", "Social Media Ready"],
  },
  {
    id: 5002,
    title: "BANNER-2",
    category: "Banners",
    description: "Strategic banner creative designed for maximum click-through and engagement.",
    image: asset("/src/assets/images/BANNERS/BANNER-2.jpg"),
    technologies: ["Conversion Design", "CTA Optimization", "Engagement Strategy"],
    features: ["Click-Optimized", "Clear CTA", "Engagement Focused"],
  },
  {
    id: 5003,
    title: "BANNER-3",
    category: "Banners",
    description: "Brand-aligned banner design maintaining consistent visual identity.",
    image: asset("/src/assets/images/BANNERS/BANNER-3.png"),
    technologies: ["Brand Consistency", "Visual Identity", "Campaign Integration"],
    features: ["Brand Aligned", "Consistent Identity", "Campaign Integrated"],
  },
  {
    id: 5004,
    title: "BANNER-4",
    category: "Banners",
    description: "Multi-format banner design adaptable across various platforms and sizes.",
    image: asset("/src/assets/images/BANNERS/BANNER-4.png"),
    technologies: ["Multi-Format", "Platform Adaptation", "Responsive Design"],
    features: ["Multi-Format", "Platform Adaptive", "Responsive Layout"],
  },

  // ===== POSTS FOLDER - Only Social Media Posts (12 items) =====
  {
    id: 6001,
    title: "POST-1",
    category: "Social Media Posts",
    description: "Engaging social media post designed for maximum reach and interaction.",
    image: asset("/src/assets/images/POSTS/POST-1.png"),
    technologies: ["Social Media Design", "Content Creation", "Engagement Strategy"],
    features: ["High Engagement", "Share-Worthy", "Platform Optimized"],
  },
  {
    id: 6002,
    title: "POST-2",
    category: "Social Media Posts",
    description: "Brand-focused social content maintaining visual consistency and messaging.",
    image: asset("/src/assets/images/POSTS/POST-2.png"),
    technologies: ["Brand Content", "Visual Consistency", "Message Alignment"],
    features: ["Brand Focused", "Consistent Visuals", "Aligned Messaging"],
  },
  {
    id: 6003,
    title: "POST-3",
    category: "Social Media Posts",
    description: "Creative social media content with compelling visuals and copy.",
    image: asset("/src/assets/images/POSTS/POST-3.png"),
    technologies: ["Creative Content", "Visual Design", "Copywriting"],
    features: ["Creative Visuals", "Compelling Copy", "Engaging Design"],
  },
  {
    id: 6004,
    title: "POST-4",
    category: "Social Media Posts",
    description: "Promotional social post highlighting products, services, or campaigns.",
    image: asset("/src/assets/images/POSTS/POST-4.png"),
    technologies: ["Promotional Design", "Product Showcase", "Campaign Promotion"],
    features: ["Promotional Focus", "Product Highlight", "Campaign Driven"],
  },
  {
    id: 6005,
    title: "POST-5",
    category: "Social Media Posts",
    description: "Educational social content providing value and building audience trust.",
    image: asset("/src/assets/images/POSTS/POST-5.png"),
    technologies: ["Content Marketing", "Educational Design", "Trust Building"],
    features: ["Educational Value", "Trust Building", "Audience Engagement"],
  },
  {
    id: 6006,
    title: "POST-6",
    category: "Social Media Posts",
    description: "Storytelling social post with narrative elements and visual flow.",
    image: asset("/src/assets/images/POSTS/POST-6.png"),
    technologies: ["Storytelling", "Narrative Design", "Visual Flow"],
    features: ["Story-Driven", "Narrative Elements", "Visual Storytelling"],
  },
  {
    id: 6007,
    title: "POST-7",
    category: "Social Media Posts",
    description: "Interactive social content designed to encourage audience participation.",
    image: asset("/src/assets/images/POSTS/POST-7.png"),
    technologies: ["Interactive Design", "Engagement Tactics", "Audience Participation"],
    features: ["Interactive Elements", "Participation Encouraged", "Engagement Tactics"],
  },
  {
    id: 6008,
    title: "POST-8",
    category: "Social Media Posts",
    description: "Trend-aware social post incorporating current design trends and styles.",
    image: asset("/src/assets/images/POSTS/post-8.png"),
    technologies: ["Trend Design", "Contemporary Style", "Trend Integration"],
    features: ["Trend-Aware", "Contemporary Design", "Style Current"],
  },
  {
    id: 6009,
    title: "POST-9",
    category: "Social Media Posts",
    description: "Conversion-focused social post with clear call-to-action and value proposition.",
    image: asset("/src/assets/images/POSTS/POST-9.png"),
    technologies: ["Conversion Design", "CTA Optimization", "Value Communication"],
    features: ["Conversion Focused", "Clear CTA", "Value Proposition"],
  },
  {
    id: 6010,
    title: "POST-10",
    category: "Social Media Posts",
    description: "Multi-platform social content optimized for various social media channels.",
    image: asset("/src/assets/images/POSTS/POST-10.png"),
    technologies: ["Multi-Platform", "Channel Optimization", "Cross-Platform Design"],
    features: ["Multi-Platform", "Channel Optimized", "Cross-Platform Ready"],
  },
  {
    id: 6011,
    title: "POST-11",
    category: "Social Media Posts",
    description: "Community-building social post fostering connection and engagement.",
    image: asset("/src/assets/images/POSTS/POST-11.png"),
    technologies: ["Community Building", "Connection Design", "Engagement Strategy"],
    features: ["Community Focus", "Connection Building", "Engagement Strategy"],
  },
  {
    id: 6012,
    title: "POST-12",
    category: "Social Media Posts",
    description: "Seasonal or event-specific social content aligned with campaigns and timing.",
    image: asset("/src/assets/images/POSTS/POST-12.png"),
    technologies: ["Seasonal Design", "Event Marketing", "Campaign Timing"],
    features: ["Seasonal Alignment", "Event Specific", "Timely Content"],
  },

  // ===== WEBSITES - Website Development Projects =====
  {
    id: 7001,
    title: "VFiler",
    category: "Websites",
    description: "Professional file management and sharing platform with modern UI/UX design.",
    image: "", // No image available
    mediaType: "image",
    technologies: ["Web Development", "UI/UX Design", "React", "Modern Stack"],
    liveUrl: "https://vfiler.com/",
    features: ["Modern Interface", "User-Friendly", "Responsive Design", "Performance Optimized"],
  },
  {
    id: 7002,
    title: "Archie Estimates",
    category: "Websites",
    description: "Construction and estimation services platform with professional business presentation.",
    image: "", // No image available
    mediaType: "image",
    technologies: ["Web Development", "Business Solutions", "Modern Design", "SEO Optimized"],
    liveUrl: "https://archiestimates.com/",
    features: ["Professional Design", "Business Focused", "SEO Optimized", "Modern Stack"],
  },
  {
    id: 7003,
    title: "Arco Experts",
    category: "Websites",
    description: "Expert consulting and services platform showcasing professional expertise.",
    image: "", // No image available
    mediaType: "image",
    technologies: ["Web Development", "Consulting Platform", "Professional Design", "User Experience"],
    liveUrl: "https://arcoexperts.com/",
    features: ["Expert Platform", "Professional Design", "User-Centric", "Modern Architecture"],
  },
  {
    id: 7004,
    title: "Radiant CS",
    category: "Websites",
    description: "Customer service and support platform with efficient communication tools.",
    image: "", // No image available
    mediaType: "image",
    technologies: ["Web Development", "Customer Service", "Modern UI", "Performance"],
    liveUrl: "https://radiantcs.com.pk/",
    features: ["Service Platform", "Efficient Design", "Customer-Focused", "High Performance"],
  },
];
